apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::049431348542:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-I0R5M2ZP7EN0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::049431348542:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-22T15:30:23Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-22T15:30:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1505"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d05aa477-23a9-41ab-8458-d6ad8662257f
  
